app/games/__init__.py
from flask import Blueprint

games = Blueprint('games', __name__)

from . import views

app/games/views.py
from flask import abort, render_template, redirect, url_for, request

from . import games
from .. import db
from ..models import Game, User

PER_PAGE = 10


@games.route('/games', defaults={'page': 1})
@games.route('/games/page/<int:page>')
def list(page):
    """Gets list of games ordered by followers and paginates"""
    games = Game.query \
        .order_by(Game.num_of_users.desc()) \
        .paginate(page, PER_PAGE, error_out=False)

    return render_template('games/games.html',
                           games=games,
                           title='Games')


@games.route('/game/<int:id>')
def get_by_id(id):
    """Returns a single game by ID"""
    game = Game.query.get_or_404(id)

    return render_template('games/game.html',
                           game=game,
                           title=game.name)


@games.route('/game/<int:game_id>/follow/<int:user_id>',
             methods=['GET', 'POST'])
def follow(game_id, user_id):
    """Follows games based on user and game ids. See implementation
    details on models.py"""
    game = Game.query.get_or_404(game_id)
    user = User.query.get_or_404(user_id)
    user.add_game(game)
    db.session.commit()

    return redirect(request.referrer or url_for('games.list'))


@games.route('/game/<int:game_id>/unfollow/<int:user_id>',
             methods=['GET', 'POST'])
def unfollow(game_id, user_id):
    """Unfollows games based on user and game ids. See implementation
    details on models.py"""
    game = Game.query.get_or_404(game_id)
    user = User.query.get_or_404(user_id)
    user.remove_game(game)
    db.session.commit()

    return redirect(request.referrer or url_for('games.list'))


@games.route('/user/<string:username>/games', defaults={'page': 1})
@games.route('/user/<string:username>/games/page/<int:page>')
def filter_by_user(username, page):
    """Returns all of a single user"""
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    games = Game.query \
        .filter(Game.users.contains(user)) \
        .paginate(page, PER_PAGE, error_out=None)

    return render_template('games/games.html',
                           games=games,
                           title='Games of ' + username)


@games.route('/games/search', methods=['POST'])
def search():
    name = request.form.get('query')
    if name is None:
        abort(404)
    return redirect(url_for('games.search_results', name=name, page=1))


@games.route('/games/search/<string:name>', defaults={'page': 1})
@games.route('/games/search/<string:name>/page/<int:page>')
def search_results(name, page):
    games = Game.query \
        .filter(Game.name.contains(name)) \
        .paginate(page, PER_PAGE, error_out=None)

    return render_template('games/games.html',
                           games=games,
                           title='Search')

app/templates/games/game.html
{% extends "base.html" %}
{% block body %}
  <div class="content-section">
    <div class="middle">
      <div class="inner">
        <br/>
        {% if game %}
        <div class="container content-section">
          <div class="row">
            <div class="col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-6">
              <div class="col-xs-12 col-sm-4">
                <figure>
                    <img src="https://via.placeholder.com/200x350" alt="" class="img-thumbnail">
                </figure>
              </div>
              <div class="col-xs-12 col-sm-8">
                <div class="row">
                  <h1>{{ game.name }}</h1>
                  <p><strong>Description: </strong> Lorem ipsum dolor sit amet,
                    consectetur adipisicing elit. Saepe rem
                    nisi accusamus error velit animi non ipsa placeat. Recusandae,
                    suscipit, soluta quibusdam accusamus a veniam quaerat eveniet
                    eligendi dolor consectetur. </p>
                </div>
                <hr>
                <div class="row text-center">
                  <div class="col-xs-12 col-sm-6">
                    <h2><strong><a href="{{ url_for('users.filter_by_game', game_id=game.id) }}">
                      {{ game.users.count() }}</a></strong></h2>
                    <p>
                      <small>Followers</small>
                    </p>
                  </div>
                  <div class="col-xs-12 col-sm-6">
                    <h2>
                      {% if current_user.is_authenticated %}
                        {% if current_user.has_game(game) %}
                          <a href="{{ url_for('games.unfollow', game_id=game.id, user_id=current_user.id) }}" class ="btn btn-success btn-block">Following</a>
                        {% else %}
                          <a href="{{ url_for('games.follow', game_id=game.id, user_id=current_user.id) }}" class ="btn btn-primary btn-block">Follow</a>
                        {% endif %}
                      {% else  %}
                        <a class="btn btn-primary btn-block disabled">Log in to follow</a>
                      {% endif %}
                    </h2>
                    <p><small>Follow</small></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

app/templates/games/games.html
{% import "bootstrap/utils.html" as utils %}
{% import "macros/search.html" as search %}
{% extends "base.html" %}
{% block body %}
  <div class="content-section">
    <div class="middle">
      <div class="inner">
        <br/>
        <h1 style="text-align:center;">Games</h1>
        <hr class="intro-divider">
        <div class="center">
          {{ search.search_widget('games.search') }}
        </div>
        {% if games.items %}
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="80%"> Name
                  <th width="5%"> <i class="fa fa-group"></i>
                  {% if current_user.is_authenticated %}
                    <th width="5%"> <i class="fa fa-check"></i>
                  {% endif %}
              <tbody>
              {% for game in games.items %}
                <tr>
                  <td>
                    <a href="{{ url_for('games.get_by_id', id=game.id) }}">
                      {{ game.name }}</a>
                  <td>
                    <a href="{{ url_for('users.filter_by_game', game_id=game.id) }}">
                      {{ game.users.count() }}</a>
                  {% if current_user.is_authenticated %}
                    <td>
                      {% if game in current_user.games %}
                        <a href="{{ url_for('games.unfollow',
                                game_id=game.id, user_id=current_user.id) }}">
                          <i class="fa fa-remove"></i></a>
                      {% else %}
                        <a href="{{ url_for('games.follow',
                                game_id=game.id, user_id=current_user.id) }}">
                          <i class="fa fa-check"></i></a>
                      {% endif %}
                  {% endif %}
              {% endfor %}
            </table>
            <nav>
              <ul class="pager">
                {% if games.has_prev %}
                  <li class="previous">
                    <a href="{{ url_for('games.list', page=games.prev_num) }}">
                      <span aria-hidden="true">&larr;</span>Previous</a>
                {% else %}
                  <li class="previous disabled">
                    <a href="javascript:void(0)">
                      <span aria-hidden="true">&larr;</span>Previous</a>
                {% endif %}

                {% if games.has_next %}
                  <li class="next">
                    <a href="{{ url_for('games.list', page=games.next_num) }}">
                      Next <span aria-hidden="true">&rarr;</span></a>
                {% else %}
                  <li class="next disabled">
                    <a href="javascript:void(0)">
                      Next <span aria-hidden="true">&rarr;</span></a>
                {% endif %}
              </ul>
            </nav>
          </div>
        {% else %}
          <div style="text-align: center">
          <h3> No games found. </h3>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}