app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Email, Optional

from ..models import Social

# TODO: add max length validator to fields
class UserForm(FlaskForm):
    """WTForm for users to edit profile"""
    email = StringField('E-mail', validators=[Optional(), Email()])
    bio = TextAreaField('Bio', render_kw={'rows': 5})
    submit_user = SubmitField('Save')

class SocialForm(FlaskForm):
    """WTForm for user social profiles"""
    reddit = StringField('Reddit')
    telegram = StringField('Telegram')
    discord = StringField('Discord')
    steam = StringField('Steam')
    origin = StringField('Origin')
    blizzard = StringField('Blizzard')
    submit_social = SubmitField('Save')

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

app/users/views.py
from string import lower

from flask import abort, render_template, url_for, redirect, request
from flask_login import login_required, current_user

from app import db
from app.users.forms import UserForm, SocialForm
from . import users
from ..models import Game, User

PER_PAGE = 10


@users.route('/users', defaults={'page': 1})
@users.route('/users/page/<int:page>')
def list(page):
    """Render list of users and paginates"""
    users = User.query.paginate(page, PER_PAGE, error_out=False)

    return render_template('users/users.html',
                           users=users,
                           title='Users')


@users.route('/user/<string:username>')
def get_by_username(username):
    """Render user profile based on username"""
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)

    return render_template('users/user.html',
                           user=user,
                           title=username)


@users.route('/game/<int:game_id>/users', defaults={'page': 1})
@users.route('/game/<int:game_id>/users/page/<int:page>')
def filter_by_game(game_id, page):
    """Returns list of users filtered by followed game"""
    game = Game.query.get_or_404(game_id)
    users = User.query \
        .filter(User.games.contains(game)) \
        .paginate(page, PER_PAGE, error_out=None)

    return render_template('users/users.html',
                           users=users,
                           title='Users following ' + game.name)


@users.route('/user/<string:username>/edit', methods=['GET', 'POST'])
@login_required
def edit_profile(username):
    """Edit profile"""
    if current_user.username != username:
        abort(403)
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    user_form = UserForm(obj=user)
    # Create SocialForm based on existing user social ids
    social_form = SocialForm(obj=user.get_socials_dict())

    # Check that UserForm is submitted
    if user_form.submit_user.data and user_form.validate_on_submit():
        user.email = user_form.email.data
        user.bio = user_form.bio.data
        db.session.commit()
        return redirect(
            url_for('users.get_by_username', username=user.username))

    # Check that SocialForm is submitted
    if social_form.submit_social.data and social_form.validate_on_submit():
        user.set_socials_by_form(social_form)
        db.session.commit()
        return redirect(
            url_for('users.get_by_username', username=user.username))

    # Renders existing data on forms
    user_form.email.data = user.email
    user_form.bio.data = user.bio
    for social_name, social_id in user.get_socials_dict().iteritems():
        social_form[lower(social_name)].data = social_id

    return render_template('users/edit_profile.html',
                           user_form=user_form,
                           social_form=social_form,
                           user=user,
                           title='Edit Profile')


@users.route('/users/search', methods=['POST'])
def search():
    username = request.form.get('query')
    if username is None:
        abort(404)
    return redirect(url_for('users.search_results', username=username, page=1))


@users.route('/users/search/<string:username>', defaults={'page': 1})
@users.route('/users/search/<string:username>/page/<int:page>')
def search_results(username, page):
    users = User.query \
        .filter(User.username.contains(username)) \
        .paginate(page, PER_PAGE, error_out=None)

    return render_template('users/users.html',
                           users=users,
                           title='Search')

app/templates/users/edit_profile.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
  Edit Profile
{% endblock %}
{% block body %}
  <div class="content-section">
    <div class="outer">
      <div class="middle">
        <div class="inner">
          <div class="center">
            <h1>Edit Profile</h1>
            <br/>
            {{ wtf.quick_form(user_form) }}
            <hr/>
            <h3>Social</h3>
            {{ wtf.quick_form(social_form) }}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/users/user.html
{% extends "base.html" %}
{% block body %}
  <div class="container intro-header">
    {% if user %}
      <div class="container content-section">
        <div class="row">
          <div class="col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-6">
            <div class="row">
              <div class="col-sm-12">
                <div class="col-xs-12 col-sm-12">
                  <h1>{{ user.username }}</h1>
                  {% if user.bio %}
                  <p><strong>Bio: </strong> {{ user.bio }}</p>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 text-center">
                <hr>
                <div class="col-xs-12 col-sm-4">
                  <h2><strong><a href="{{ url_for('games.filter_by_user', username=user.username) }}">
                      {{ user.games.count() }}</a> </strong></h2>
                  <p>
                    <small>Games followed</small>
                  </p>
                </div>
                <div class="col-xs-12 col-sm-4">
                  {% set socials = user.get_socials_dict() %}
                  <dl class="dl-horizontal dl-profile">
                    {% if socials['Telegram'] %}<dt>Telegram</dt><dd>{{ socials['Telegram'] }}</dd>{% endif %}
                    {% if socials['Discord'] %}<dt>Discord</dt><dd>{{ socials['Discord'] }}</dd>{% endif %}
                    {% if socials['Reddit'] %}<dt>Reddit</dt><dd>{{ socials['Reddit'] }}</dd>{% endif %}
                    {% if not (socials['Telegram'] or socials['Discord'] or socials['Reddit']) %}
                      <small>This user hasn't added any social platform profile yet :(</small>
                    {% endif %}
                  </dl>
                <p><small>Get in touch</small></p>
                </div>
                <div class="col-xs-12 col-sm-4">
                  <dl class="dl-horizontal  dl-profile">
                    {% if socials['Steam'] %}<dt>Steam</dt><dd>{{ socials['Steam'] }}</dd>{% endif %}
                    {% if socials['Origin'] %}<dt>Origin</dt><dd>{{ socials['Origin'] }}</dd>{% endif %}
                    {% if socials['Blizzard'] %}<dt>Blizzard</dt><dd>{{ socials['Blizzard'] }}</dd>{% endif %}
                    {% if not (socials['Steam'] or socials['Origin'] or socials['Blizzard']) %}
                        <small>This user hasn't added any gaming platform profile yet :(</small>
                    {% endif %}
                  </dl>
                    <small>Play together</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

app/templates/users/users.html
{% import "bootstrap/utils.html" as utils %}
{% import "macros/search.html" as search %}
{% extends "base.html" %}
{% block body %}
  <div class="content-section">
    <div class="middle">
      <div class="inner">
        <br/>
        <h1 style="text-align:center;">Users</h1>
        <hr class="intro-divider">
        <div class="center">
          {{ search.search_widget('users.search') }}
        </div>
        {% if users.items %}
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="80%"> Username
                  <th width="20%"> Games followed
              <tbody>
              {% for user in users.items %}
                <tr>
                  <td>
                    <a href="{{ url_for('users.get_by_username', username=user.username) }}">
                      {{ user.username }}</a>
                  <td>
                    <a href="{{ url_for('games.filter_by_user', username=user.username) }}">
                      {{ user.games.count() }}</a>
              {% endfor %}
            </table>
            <nav>
              <ul class="pager">
                {% if users.has_prev %}
                  <li class="previous">
                    <a href="{{ url_for('users.list', page=users.prev_num) }}">
                      <span aria-hidden="true">&larr;</span>Previous</a>
                {% else %}
                  <li class="previous disabled">
                    <a href="javascript:void(0)">
                      <span aria-hidden="true">&larr;</span>Previous</a>
                {% endif %}

                {% if users.has_next %}
                  <li class="next">
                    <a href="{{ url_for('users.list', page=users.next_num) }}">
                      Next <span aria-hidden="true">&rarr;</span></a>
                {% else %}
                  <li class="next disabled">
                    <a href="javascript:void(0)">
                      Next <span aria-hidden="true">&rarr;</span></a>
                {% endif %}
              </ul>
            </nav>
          </div>
        {% else %}
          <div style="text-align: center">
          <h3> No users found. </h3>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}